version: '3.3'

services:
  fpm:
    image: php:7.2-fpm
    container_name: otus.fpm
    depends_on:
      - php

  php:
    build:
      context: Settings/Docker/php
    container_name: otus.php
    volumes:
      - /usr/local/www/otus/social.network:/usr/local/www/otus/social.network
    networks:
      - code-network

  nginx:
    image: nginx:latest
    container_name: otus.nginx
    volumes:
      - /usr/local/www/otus/social.network:/usr/local/www/otus/social.network
      - /usr/local/www/otus/social.network/Settings/Docker/nginx/conf.d/social.network.conf:/etc/nginx/conf.d/social.network.conf
    ports:
      - 82:82
    networks:
      - code-network
    depends_on:
      - fpm

  mysql:
    image: mysql:latest
    container_name: otus.mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0cd
    environment:
      - MYSQL_ROOT_PASSWORD=dinhO959
      - MYSQL_USER=parovozzzik
      - MYSQL_PASSWORD=dinhO959
      - MYSQL_DATABASE=social.network
    ports:
      - 3307:3307
    networks:
      - code-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: otus.phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
    volumes:
      - /sessions
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8001:8001
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
