version: '3.3'

services:
  fpm:
    image: php:7.2-fpm
    container_name: otus.fpm
    depends_on:
      - php

  php:
    build:
      context: App/Settings/Docker/php
    container_name: otus.php
    volumes:
      - /usr/local/www/otus/social.network:/usr/local/www/otus/social.network
    networks:
      - code-network

  nginx:
    image: nginx:latest
    container_name: otus.nginx
    volumes:
      - /usr/local/www/otus/social.network:/usr/local/www/otus/social.network
      - /usr/local/www/otus/social.network/App/Settings/Docker/nginx/conf.d/social.network.conf:/etc/nginx/conf.d/social.network.conf
    ports:
      - 82:82
    networks:
      - code-network
    depends_on:
      - fpm

  mysql_master:
    image: mysql:5.7
    env_file:
      - App/Settings/DockerLocal/mysql/master/mysql.master.env
    container_name: otus.mysql.master
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: "no"
    ports:
      - 4406:3306
    volumes:
      - /usr/local/var/www/otus/social.network/App/Settings/DockerLocal/mysql/master/conf/mysql.master.conf.cnf:/etc/mysql/conf.d/mysql.master.conf.cnf
      - /usr/local/var/www/otus/social.network/App/Settings/DockerLocal/mysql/master/data:/var/lib/mysql
    networks:
      - code-network

    mysql_slave:
      image: mysql:5.7
      env_file:
        - App/Settings/DockerLocal/mysql/slave/mysql.slave.env
      container_name: otus.mysql.slave
      command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
      restart: "no"
      ports:
        - 5506:3306
      depends_on:
        - mysql_master
      volumes:
        - /usr/local/var/www/otus/social.network/App/Settings/DockerLocal/mysql/slave/conf/mysql.slave.conf.cnf:/etc/mysql/conf.d/mysql.slave.conf.cnf
        - /usr/local/var/www/otus/social.network/App/Settings/DockerLocal/mysql/slave/data:/var/lib/mysql
      networks:
        - code-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: otus.phpmyadmin
    environment:
      - PMA_ARBITRARY=0
      - PMA_HOST=mysql
      - PMA_PORT=3306
    volumes:
      - /sessions
    depends_on:
      - mysql_master
    links:
      - mysql_master
    ports:
      - 8082:80
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
